### PR TITLE
Simple openmd simulation

### PR DESCRIPTION
**Pull request by mvala**
Please test it and let me know if ok. Don't merge it yet. We need to meet personally first

### CODE REVIEW

**Comment by mvala** [comment]
When can we meet? For me it would be best to meet sometimes next week. Monday, Tuesday

**Comment by tmtobias** [comment]
Monday and Tuesday are good for me too. Monday from 7:00 to 15:00. Tuesday from 7:00 to 11:00.

**Comment by mvala** [comment]
Please remind me in this issue about meeting. Just post something

**Comment by tmtobias** [comment]
OK, I'll remind you.

**Comment by tmtobias** [comment]
We should meet today.

**Pull request merged**
